# Generated by Django 3.0.5 on 2020-10-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_currency_currencyrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ('label',)},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_label',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_name',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='currency_label',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='currency_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='label',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='rate',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
